# version: '3'

services:

  # create and setup postgresql database
  db:
#    profiles: ['db', 'all']
    image: postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: scene_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

  # create and setup Flyway for managing migrations/seed-data
  flyway:
#    profiles: ['db', 'all']
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/scene_db -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - db

  # create and setup Express API container - creating your own image
  api:
    profiles: ['api', 'all']
    image: scene-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/scene_db?schema=public"
  
    # create and setup UI container - creating your own image
  ui:
    profiles: ['ui', 'all']
    image: scene-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/src

volumes:
  db:
