# version: '3'

services:

  # create and setup postgresql database
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: scene_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

  # create and setup Flyway for managing migrations/seed-data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/scene_db -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - db

  # create and setup Express API container - creating your own image
  api:
    image: scene-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/scene_db?schema=public"

volumes:
  db: