name: Verify Server Integration Tests

on:
  #pull_request:
  push:
    #paths:
    #  - 'server/**'
    #  - 'db/**'

defaults:
  run:
    working-directory: ./server

env:
  DATABASE_URL: postgresql://postgres:password@localhost:5435/donations?schema=public

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm i
      - name: Test
        run: npm run test:integration